run:
  timeout: 5m

linters:
  enable:
    - errname
    - exhaustive
    - gci
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - godot
    - gofumpt
    - goheader
    - goimports
    - gosec
    - ifshort
    - importas
    - ireturn
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testpackage
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    - wsl
